### ISSUE TITLE
Need help to implement facelandmarks extraction in xamarin forms

### ISSUE THREAD

**Issue by amalcty** [vignetteapp/MediaPipe.NET.Runtime#12]
Can you please provide a demo script to extract facial landmarks from a given image in xamarin forms ?
 It would be great if you provide some kind of documentation too for using the library.

**Comment by Speykious** [comment]
MediaPipe.NET.Runtime only serves to compile the runtime package that contains the native MediaPipe DLL.
The actual C# bindings and additional abstractions can be found on [MediaPipe.NET](https://github.com/vignetteapp/MediaPipe.NET).
This issue is better suited for that repository. :)
